/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-2.30.6-gf6a602e (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.30.6-gf6a602e"
#endif
#define SDL_REVISION_NUMBER 0
